stages:
  - test-and-coverage
  - deploy


# Builds IPPL with -O0 in debug mode with coverage metrics and runs tests. Only results are stored since those files can get very large
test-and-coverage:
  stage: test-and-coverage
  image: registry.jsc.fz-juelich.de/muralikrishnan1/ippl:latest
  tags:
    - test
  script:
    - echo "Building IPPL with tests and coverage enabled"
    - /usr/local/bin/compile.sh
    - echo "Running tests"

    - cd build
    - ASAN_OPTIONS="detect_leaks=0" ctest -j 16 --output-on-failure --output-junit tests/test_results.xml
    - echo "Generage coverage report"
    - /usr/local/bin/coverage_report.sh
  artifacts:
    paths:
      - build/coverage_report
      - build/tests

pages:
  stage: deploy
  dependencies:
    - test-and-coverage
  script:
    - mkdir -p public
    - cp -r build/coverage_report/* public/
  artifacts:
    paths:
      - public
  when: manual
