stages:
  - run-container

run-docker-container:
  stage: run-container
  image: registry.jsc.fz-juelich.de/muralikrishnan1/ippl:latest
  tags: 
    - test 
  script:
    - echo "Starting build process for IPPL"
    - mkdir -p build                   
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DENABLE_TESTS=True -DENABLE_FFT=ON -DENABLE_SOLVERS=ON -DENABLE_UNIT_TESTS=True -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_COVERAGE=OFF -DKokkos_VERSION=4.2.00
    - make
