pages:
  stage: deploy
  image: registry.jsc.fz-juelich.de/muralikrishnan1/ippl:latest
  tags:
    - test
  script:
    - echo "hello"
  artifacts:
    paths:
      - public
  variables:
    GITLAB_ACCESS_TOKEN: "${CI_GITLAB_ACCESS_TOKEN}"  # Read from CI/CD variables
